### ISSUE TITLE
Google no longer allows Less Secure Apps, which impacts `smtp_send()`

### ISSUE THREAD

**Issue by richpauloo** [rstudio/blastula#288]
As of 2022-05-30, Google ended support for "Less Secure Apps" ([see announcement](https://support.google.com/accounts/answer/6010255)). This affects blastula emails sent over gmail's SMTP servers.

The [blastula docs](https://pkgs.rstudio.com/blastula/articles/sending_using_smtp.html#requirement-for-using-gmail) hinge on using Less Secure Apps to send email via `smpt_send()`.

If I'm not mistaken, Less Secure Apps are now deprecated as of almost 2 weeks ago. I noticed only because I have code on a cron job that uses `smtp_send()` based on a creds file and App password that stopped working 2022-06-01. I've tried to revert Google Security settings back to allow Less Secure Apps, but it seems these days are behind us (see screenshot below). The "Learn More" link in the image below takes you to the deprecation announcement (first link above).

![image](https://user-images.githubusercontent.com/10336683/173179553-9f8c7407-cb26-4785-b72d-df7c1df1d5ee.png)

Finally, thank you so much for this amazing 📦 !

**Comment by nguyens7** [comment]
The blastula docs page has updated information that suggests using an **[app password](https://support.google.com/accounts/answer/185833?hl=en)** since Google deprecated the Less Secure Apps option.  https://rstudio.github.io/blastula/articles/sending_using_smtp.html
<img width="818" alt="Screen Shot 2022-09-23 at 2 20 50 PM" src="https://user-images.githubusercontent.com/18275928/192032276-2e39053f-1e3d-4086-8159-bcc500657c12.png">

**Comment by rich-iannone** [comment]
Thanks @nguyens7 for answering this! Will close the issue now.
